dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install -r requirements.txt
script:
  - pytest -v
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  edge: true
  on:
    tags: true